//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace FrameWorkExample
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DbCompanyEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DbCompanyEntities object using the connection string found in the 'DbCompanyEntities' section of the application configuration file.
        /// </summary>
        public DbCompanyEntities() : base("name=DbCompanyEntities", "DbCompanyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DbCompanyEntities object.
        /// </summary>
        public DbCompanyEntities(string connectionString) : base(connectionString, "DbCompanyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DbCompanyEntities object.
        /// </summary>
        public DbCompanyEntities(EntityConnection connection) : base(connection, "DbCompanyEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Emp> Emps
        {
            get
            {
                if ((_Emps == null))
                {
                    _Emps = base.CreateObjectSet<Emp>("Emps");
                }
                return _Emps;
            }
        }
        private ObjectSet<Emp> _Emps;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Emps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmps(Emp emp)
        {
            base.AddObject("Emps", emp);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbCompanyModel", Name="Emp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Emp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Emp object.
        /// </summary>
        /// <param name="empno">Initial value of the Empno property.</param>
        public static Emp CreateEmp(global::System.Int16 empno)
        {
            Emp emp = new Emp();
            emp.Empno = empno;
            return emp;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Empno
        {
            get
            {
                return _Empno;
            }
            set
            {
                if (_Empno != value)
                {
                    OnEmpnoChanging(value);
                    ReportPropertyChanging("Empno");
                    _Empno = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Empno");
                    OnEmpnoChanged();
                }
            }
        }
        private global::System.Int16 _Empno;
        partial void OnEmpnoChanging(global::System.Int16 value);
        partial void OnEmpnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ename
        {
            get
            {
                return _Ename;
            }
            set
            {
                OnEnameChanging(value);
                ReportPropertyChanging("Ename");
                _Ename = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ename");
                OnEnameChanged();
            }
        }
        private global::System.String _Ename;
        partial void OnEnameChanging(global::System.String value);
        partial void OnEnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Job
        {
            get
            {
                return _Job;
            }
            set
            {
                OnJobChanging(value);
                ReportPropertyChanging("Job");
                _Job = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Job");
                OnJobChanged();
            }
        }
        private global::System.String _Job;
        partial void OnJobChanging(global::System.String value);
        partial void OnJobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Salary
        {
            get
            {
                return _Salary;
            }
            set
            {
                OnSalaryChanging(value);
                ReportPropertyChanging("Salary");
                _Salary = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Salary");
                OnSalaryChanged();
            }
        }
        private Nullable<global::System.Int16> _Salary;
        partial void OnSalaryChanging(Nullable<global::System.Int16> value);
        partial void OnSalaryChanged();

        #endregion

    
    }

    #endregion

    
}
